// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://txtgrxwulaqyfxdyxnik.supabase.co';
// This is the public anon key (safe to use in the frontend)
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4dGdyeHd1bGFxeWZ4ZHl4bmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxMzUxMTUsImV4cCI6MjA4MjcxMTExNX0.IjegJmWqU65BwIMwvptDoSuazADS5DT6LzmMS3eicRs';
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});